// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.210
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HtmlView
{
				static class Vsix
				{
								public const string Id = "HtmlView.MISoftware.57ef93d2-bc83-4264-b2f4-c9a5eb66faa1";
								public const string Name = "HtmlView";
								public const string Description = @"Provides the HTML editor an area where it shows a preview of your HTML page. Essentially it is a Chrome based browser inside Visual Studio showing your HTML page.";
								public const string Language = "en-US";
								public const string Version = "1.6";
								public const string Author = "MI Software";
								public const string Tags = "HTML,HTML5,CSS,JS,CEF,Chrome,Productivity,Preview";
				}
}
